// Generated by CoffeeScript 1.7.1

/*
 * evemit
 * evemit.emptystack.net
 *
 * Copyright (c) 2014 Eric Wang
 * Licensed under the MIT license.
 */
define(function(require, exports, module) {
  'use strict';
  var _isIE;
  _isIE = window.addEventListener != null ? false : true;
  exports.bind = function(el, eve, fn, priority) {
    return el[_isIE ? "attachEvent" : "addEventListener"]("" + (_isIE ? 'on' : '') + eve, fn, priority || false);
  };
  exports.unbind = function(el, eve, fn, priority) {
    return el[_isIE ? "detachEvent" : "removeEventListener"]("" + (_isIE ? 'on' : '') + eve, fn, priority || false);
  };
});
